# Generated by Django 5.2.11 on 2026-02-10 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datafile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to='datasets/')),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Processing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='agent_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(editable=False)),
                ('actions_to_take', models.TextField(editable=False)),
                ('gear_Status', models.CharField(choices=[('Wear', 'Wear'), ('RootCrack', 'RootCrack'), ('MissingTooth', 'MissingTooth'), ('Healthy', 'Healthy'), ('Broken', 'Broken')], default='NIL', editable=False, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.datafile')),
            ],
        ),
    ]
