# Generated by Django 5.2.11 on 2026-02-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='upload',
            field=models.FileField(unique=True, upload_to='datasets/'),
        ),
    ]
