# Generated by Django 5.2.11 on 2026-02-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_datafile_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'ordering': ['-created_at']},
        ),
    ]
